# Sourcing external config files

# Default Configs
$configs = $HOME/.config/hypr/configs

exec-once = source ~/.config/hypr/hyprland.env
source = $configs/settings.conf
source = $configs/keybinds.conf
source = $configs/startup.conf
source = $configs/variables.conf
source = $configs/window_rules.conf
source = $configs/animations.conf
source = $configs/monitors.conf

