windowrulev2 = idleinhibit fullscreen, fullscreen:1

windowrule = float on, match:title (org.kde.polkit-kde-authentication-agent-1)
windowrule = float on, match:title (nm-connection-editor|blueman-manager)
windowrule = float on, match:title (pavucontrol)
windowrule = float on, match:title (eog) # Eye of gnome
windowrule = float on, match:title (rofi)
windowrule = float on, match:title (gnome-system-monitor)
windowrule = float on, match:title (yad)

#opacity (transparent) #enable as desired
#first value: focused, second:not focused
windowrulev2 = opacity 0.9 0.6, class:^[Rr]ofi)$
windowrulev2 = opacity 0.9 0.8, class:^(kitty)$
windowrulev2 = opacity 0.9 0.7, class:^(yad)$
windowrulev2 = opacity 0.9 0.7, class:^(Spotify)$
windowrulev2 = opacity 0.9 0.7, class:^(steam)$
# windowrulev2 = opacity 1, 1, title:^(Picture-in-Picture)$

# Blur -----------------------------------------------------
  # Wlogout
layerrule = blur on, match:title logout_dialog

layerrule = blur on, match:class (^(swww)$)
layerrule = blur on, match:title rofi
#layerrule = blur, (waybar)

layerrule = blur off, match:title swaync-control-center
layerrule = blur off, match:title swaync-notification-window

# Tweaks to work with blur -----------------------------------

# layerrule = unset on, match:title rofi
# layerrule = ignorezero on, match:title rofi
#
# layerrule = ignorezero on, match:title swaync-control-center
# layerrule = ignorezero on, match:title swaync-notification-window
#
# layerrule = ignorealpha 0.5, match:title swaync-control-center
# layerrule = ignorealpha 0.5, match:title swaync-notification-window

# Picture-in-a-Picture (PIP) rules: Oddly, some need re-duplication.  This is because the window for
# PIP changes after on first launch, and will not inherant the rules...
windowrulev2=opacity 0.95 0.75, match:title (^(Picture-in-Picture)$) # for opacity: [focus num] [bg num]
# Interestingly, the opacity rule above doesn't need the reduplication?
windowrulev2=pin on, match:title (^(Picture-in-Picture)$ )
windowrulev2=float on, match:title (^(Picture-in-Picture)$)
windowrulev2=size 25% 25%, match:title (^(Picture-in-Picture)$ )
windowrulev2=move 72% 7%, match:title (^(Picture-in-Picture)$ )

windowrulev2 = opacity 0.0 override 0.0 override, match:class (^(xwaylandvideobridge)$)
windowrulev2 = noanim on, match:class (^(xwaylandvideobridge)$)
windowrulev2 = noinitialfocus on, match:class (^(xwaylandvideobridge)$)
windowrulev2 = maxsize 1 1, match:class (^(xwaylandvideobridge)$)
windowrulev2 = noblur on, match:class (^(xwaylandvideobridge)$)
    

