windowrule = idle_inhibit fullscreen

windowrule = float on, match:title (org.kde.polkit-kde-authentication-agent-1)
windowrule = float on, match:title (nm-connection-editor|blueman-manager)
windowrule = float on, match:title (pavucontrol)
windowrule = float on, match:title (eog) # Eye of gnome
windowrule = float on, match:title (rofi)
windowrule = float on, match:title (gnome-system-monitor)
windowrule = float on, match:title (yad)

#opacity (transparent) #enable as desired
#first value: focused, second:not focused
windowrule = opacity 0.9 0.6, match:class ^[Rr]ofi)$
windowrule = opacity 0.9 0.8, match:class ^(kitty)$
windowrule = opacity 0.9 0.7, match:class ^(yad)$
windowrule = opacity 0.9 0.7, match:class ^(Spotify)$
windowrule = opacity 0.9 0.7, match:class ^(steam)$
# windowrule = opacity 1, 1, title:^(Picture-in-Picture)$

# Blur -----------------------------------------------------
  # Wlogout
layerrule = blur on, match:title logout_dialog

layerrule = blur on, match:class (^(swww)$)
layerrule = blur on, match:title rofi
#layerrule = blur, (waybar)

layerrule = blur off, match:title swaync-control-center
layerrule = blur off, match:title swaync-notification-window

# Tweaks to work with blur -----------------------------------

# layerrule = unset on, match:title rofi
# layerrule = ignorezero on, match:title rofi
#
# layerrule = ignorezero on, match:title swaync-control-center
# layerrule = ignorezero on, match:title swaync-notification-window
#
# layerrule = ignorealpha 0.5, match:title swaync-control-center
# layerrule = ignorealpha 0.5, match:title swaync-notification-window

# Picture-in-a-Picture (PIP) rules: Oddly, some need re-duplication.  This is because the window for
# PIP changes after on first launch, and will not inherant the rules...
windowrule=opacity 0.95 0.75, match:title (^(Picture-in-Picture)$) # for opacity: [focus num] [bg num]
# Interestingly, the opacity rule above doesn't need the reduplication?
windowrule=pin on, match:title (^(Picture-in-Picture)$ )
windowrule=float on, match:title (^(Picture-in-Picture)$)
windowrule=size 25% 25%, match:title (^(Picture-in-Picture)$ )
windowrule=move 72% 7%, match:title (^(Picture-in-Picture)$ )

windowrule = opacity 0.0 override 0.0 override, match:class (^(xwaylandvideobridge)$)
windowrule = no_anim on, match:class (^(xwaylandvideobridge)$)
windowrule = no_initial_focus on, match:class (^(xwaylandvideobridge)$)
windowrule = max_size 1 1, match:class (^(xwaylandvideobridge)$)
windowrule = no_blur on, match:class (^(xwaylandvideobridge)$)
    

