#environment-variables
env = CLUTTER_BACKEND,wayland
env = GDK_BACKEND,wayland,x11
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt5ct  
env = QT_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

#firefox
env = MOZ_ENABLE_WAYLAND,1

# gtk (gtk3 & gtk4) dark theme
env = gtk_theme,Adwaita:dark
env = gtk_application_prefer_dark_theme,1

# cursor theme & size
env = HYPRCURSOR_THEME,phinger:dark
env = HYPRCURSOR_SIZE,24
env = xcursor_theme,phinger:dark
env = xcursor_size,24

# qt apps follow gtk theme
env = qt_qpa_platformtheme,gtk

# force gdk scaling/dpi consistency
env = gdk_scale,1
env = gdk_dpi_scale,1

# optional: set default desktop name
env = xdg_current_desktop,hyprland

# GTK2
env = GTK2_RC_FILES,"$HOME/.config/gtk-2.0/gtkrc"

